language: node_js
node_js:
  - "6"

before_script:
 - npm install
 - psql -c 'create database "test";' -U postgres

script:
 - npm run test

after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage


addons:
  code_climate:
    repo_token:  MWcKaFmbxiE5AkImDD3xnxBKXdoIsIdEi

